### PR TITLE
Start hiding internal WebServer class from user

### PR DESCRIPTION
**Pull request by mmuetzel**
This adds a couple new methods to the `Html` class that allows easy access to the web server from the Charts objects.

It also fixes the destructor of the WebServer class that couldn't be called previously (because it had private access).

### CODE REVIEW

**Comment by pr0m1th3as** [comment]
Thanks for the PR. I really like the idea that users will start the WebServer independently of the Chart objects, since it is only initiated once in an Octave session. Nevertheless, if you find it useful to add your proposed methods in the `Html` class, please add some documentation in `texinfo` format, in a similar fashion to other methods. IMHO, the `webserve` method may be helpful to users who just want to directly visualize their chart, however for those who might want particular settings other than the default, I think these users are better of starting a web instance directly from the `WebServer` class rather than using a `webinitialize` method from their Chart object. This way we can keep minimal clutter in available methods that their purpose overlaps as well as their documentation. 

Please add a "DO NOT USE BY YOURSELF! in the destructors docstring.

**Comment by mmuetzel** [comment]
The web server will still be initiated only once per Octave session. But the user won't need to care about that. They would just call the `webserve` method of any of the Chart objects. The server would start automatically if it isn't running yet. Otherwise, the running instance would be updated with the new string.
Only if the user would like to start the server with non-default settings, they would need to use the `webinitialize` method.

**Comment by pr0m1th3as** [comment]
> Only if the user would like to start the server with non-default settings, they would need to use the `webinitialize` method.

Do you think this really useful since the `WebServer.start` method is already there? What is the benefit of that?

**Comment by mmuetzel** [comment]
> Do you think this really useful since the `WebServer.start` method is already there? What is the benefit of that?

The benefit would be that you could probably move the `WebServer` class to the `private` folder. That would avoid potential issues if users try to call the destructor of the singleton instance of that class manually.
Many users don't read documentation unfortunately...

**Comment by mmuetzel** [comment]
> IMHO, the `webserve` method may be helpful to users who just want to directly visualize their chart

If the users should be able to serve arbitrary HTML, it would probably be easy to adapt the `webserve` method of the `Html` class to allow that.

**Comment by pr0m1th3as** [comment]
> The benefit would be that you could probably move the `WebServer` class to the `private` folder.

I really need this Class public. See my comment on [discourse](https://octave.discourse.group/t/how-to-use-ctrl-c-signal-to-terminate-a-crow-instance-inside-an-oct-function/5896/54?u=pr0m1th3as). 


> If the users should be able to serve arbitrary HTML, it would probably be easy to adapt the `webserve` method of the `Html` class to allow that.

They can already do this with the `update()` method from `WebServer` class. I think `webserve` method of the `Html` class should just be a direct easy way to display the Chart on the `localhost:8080` so that users can see how their chart looks like. Adding further complexity to the `webserve` method will more likely result in confusion rather than help users with more options. This is the rationale behind my objection to the `webinitialize` method. Setting up the web instance with non-default for use through a proxy or some sort of deployment should be left to the `WebServer` class.

Using a method of a `Chart` object to serve arbitrary HTML content kind of misses the point, imho. Please, just keep it strictly to serving the Chart object itself without the user having to worry about starting a web instance etc.

**Comment by mmuetzel** [comment]
Well, we fundamentally disagree then. It is dangerous to expose the singleton class `WebServer` to the end user. And had I known that that was your plan, I would never have proposed it to you.

Since you are the maintainer of this package, feel free to close this PR.

> Using a method of a Chart object to serve arbitrary HTML content kind of misses the point, imho. Please, just keep it strictly to serving the Chart object itself without the user having to worry about starting a web instance etc.

If that is the case, use a class similar to the `Html` class (but that isn't inherited by the `*Chart` classes) to allow that. But don't let the user interact directly with the singleton `WebServer` class...

**Comment by pr0m1th3as** [comment]
What about if we rename `WebServer` to `WebInstance` (or something similar) and make it private and then change the `WebServer`to make it similar to Html and keep the `start` static method and the `update` method? Would this avoid exposing the singleton class to the users?

My point is that I want the `start` + `update` methods in a public Class so it can be reused by projects outside the `chartjs` package. If we can do this and avoid the danger, so much the better.

**Comment by mmuetzel** [comment]
That sounds like a better plan to me.

See the updates to this PR (that are currently untested).

**Pull request merged**
